### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by juippis** [APN-Pucky/pkg-testing-tools#17]
Hey, 

for some reason 0.2.1 is really bad at calculating multiple use flag combinations. It can take **hours** to finish simple calculation before anything happens. -9999 (git-version) seems to work instantly, so could you tag a new release? :)

**Comment by APN-Pucky** [comment]
Sure, I don't know why I did not get a email for this issue tho ...

**Comment by APN-Pucky** [comment]
BTW. what do you think about forcefully removing each package before testing/installing it using sth. like `emerge --unmerge`. I do not see any drawback, just a cleaner install env.
Just to make sure there are no old files are still around and picked up wrongly by tests (cf. https://github.com/gentoo/gentoo/pull/35746#discussion_r1526393529)

**Comment by APN-Pucky** [comment]
https://github.com/gentoo/gentoo/pull/35746#discussion_r1526393529

**Comment by juippis** [comment]
Thanks for the release!


> BTW. what do you think about forcefully removing each package before testing/installing it (again) using sth. like `emerge --unmerge`. I do not see any drawback, just a cleaner install env. Just to make sure there are no old files are still around and picked up wrongly by tests (cf. [gentoo/gentoo#35746 (comment)](https://github.com/gentoo/gentoo/pull/35746#discussion_r1526393529))

Personally not a huge fan, this issue hasn't come up to me nearly ever. And it most likely wouldn't prevent the problem happening while upgrading either. But I see you added a new `-C` option so as it's optional it's totally fine.
