### ISSUE TITLE
Calculating --max-use-combinations takes.... a very long time

### ISSUE THREAD

**Issue by juippis** [APN-Pucky/pkg-testing-tools#28]
To debug:
**pkg-testing-tool --test-feature-scope never --append-required-use '!pgo' --max-use-combinations 6 -p '=www-client/firefox-125.0.1'**

If doing 1 run, with `--max-use-combinations 1` it is instant. But with `--max-use-combinations 6` I'm 2 hours into calculating use flag combos without result yet.

This is a familiar issue with e.g. qemu and libreoffice, but it hasn't been this "bad" with Firefox before. The use flag combo calculation has been instant. `--append-required-use` has no effect, I tried to remove the option and even adding `!llvm_slot` there.

This is on 0.2.2. Without trying, I'm sure downgrading to 0.1.2 makes it better.

**Comment by juippis** [comment]
Well, I did downgrade to 0.1.2 and it worked instantly :)

**Comment by APN-Pucky** [comment]
I received a email now :). I'll check it out. I've been running 0.2.4 with only https://github.com/APN-Pucky/pkg-testing-tools/issues/27 as a problem, so I'll fix both with 0.2.5.

**Comment by juippis** [comment]
Then again calculating use flag combos for firefox-115.10.0 is instant too, so something in firefox-125.0.1 (probably 124+) makes the tool lose it's focus. It has at least valgrind and jumbo-build use flags, along with the new llvm_use USE_EXPAND compared to 115.10.0.

**Comment by APN-Pucky** [comment]
Oh, with 0.2.2 I also get straight to `Running (1 of 6)`. Only idea I have left for that issue would be a different python version (I am on python3.11).

**Comment by juippis** [comment]
It does seem to be about the patches indeed. I should finally move all my containers to utilize profile/package.use.mask instead of pkg-testing-tool patches

0.2.2 works fine after all :) I do wonder what use flag restriction specifically is causing it, but it doesn't matter since I should move to use profiles anyway in future.
